[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)][string]$OutputPath,
    [string]$SkillRoot,
    [switch]$EnableFeishu,
    [string]$FeishuWrapperPath,
    [string]$FeishuPackageCache,
    [ValidateSet('tenant','oauth','user')][string]$FeishuAuthMode = 'tenant',
    [string]$FeishuDomain = 'https://open.feishu.cn',
    [string[]]$EnableSkills = @(),
    [switch]$Overwrite
)

$ErrorActionPreference = 'Stop'

function ConvertTo-TomlString([string]$Value) {
    return '"' + $Value.Replace('\', '\\').Replace('"', '\"') + '"'
}

$scriptContainer = $PSScriptRoot
$candidateRoot = Split-Path -Parent $scriptContainer
if (Test-Path -LiteralPath (Join-Path $scriptContainer 'pack.json') -PathType Leaf) {
    $kitRoot = $scriptContainer
} elseif (Test-Path -LiteralPath (Join-Path $candidateRoot 'manifest\skill-audit.json') -PathType Leaf) {
    $kitRoot = $candidateRoot
} else {
    throw 'Cannot locate the capability-kit root.'
}

$userProfile = [Environment]::GetEnvironmentVariable('USERPROFILE')
if ([string]::IsNullOrWhiteSpace($userProfile)) { throw 'USERPROFILE is required.' }
if ([string]::IsNullOrWhiteSpace($SkillRoot)) { $SkillRoot = Join-Path $userProfile '.agents\skills' }
if ([string]::IsNullOrWhiteSpace($FeishuWrapperPath)) { $FeishuWrapperPath = Join-Path $userProfile '.codex\codex-agent-kit\bin\start-feishu-mcp.ps1' }
if ([string]::IsNullOrWhiteSpace($FeishuPackageCache)) { $FeishuPackageCache = Join-Path $userProfile '.codex\codex-agent-kit\runtime\feishu' }

$auditPath = Join-Path $kitRoot 'manifest\skill-audit.json'
$templatePath = Join-Path $kitRoot 'config-fragments\feishu-official-stdio.template.toml'
if (-not (Test-Path -LiteralPath $auditPath -PathType Leaf)) { throw "Missing Skill audit: $auditPath" }
if (-not (Test-Path -LiteralPath $templatePath -PathType Leaf)) { throw "Missing Feishu template: $templatePath" }
$audit = Get-Content -LiteralPath $auditPath -Raw -Encoding UTF8 | ConvertFrom-Json

$skillRootFull = [IO.Path]::GetFullPath($SkillRoot)
$lines = [System.Collections.Generic.List[string]]::new()
$lines.Add('# Generated by codex-starter-kit. Review and merge manually into ~/.codex/config.toml.')
$lines.Add('# No credential values are stored in this fragment.')
$lines.Add('')
$nonCore = @($audit.skills | Where-Object { [string]$_.afterRemediationStatus -ne 'core-ready' } | Sort-Object id)
$nonCoreIds = @($nonCore | ForEach-Object { [string]$_.id })
$requestedSkills = @($EnableSkills | Where-Object { -not [string]::IsNullOrWhiteSpace([string]$_) } | ForEach-Object { [string]$_ } | Sort-Object -Unique)
$unknownSkills = @($requestedSkills | Where-Object { $_ -notin $nonCoreIds })
if ($unknownSkills.Count -gt 0) { throw "Cannot enable unknown or core Skill IDs: $($unknownSkills -join ', ')" }
foreach ($skill in $nonCore) {
    $skillFile = Join-Path (Join-Path $skillRootFull ([string]$skill.id)) 'SKILL.md'
    $lines.Add('[[skills.config]]')
    $lines.Add('path = ' + (ConvertTo-TomlString $skillFile))
    $lines.Add('enabled = ' + $(if ($requestedSkills -contains [string]$skill.id) { 'true' } else { 'false' }))
    $lines.Add('')
}

if ($EnableFeishu) {
    if (-not (Test-Path -LiteralPath $FeishuWrapperPath -PathType Leaf)) { throw "Feishu wrapper not found: $FeishuWrapperPath" }
    foreach ($name in @('FEISHU_APP_ID','FEISHU_APP_SECRET')) {
        if ([string]::IsNullOrWhiteSpace([Environment]::GetEnvironmentVariable($name, 'Process'))) { throw "$name is required before enabling Feishu." }
    }
    if ($FeishuAuthMode -eq 'user' -and [string]::IsNullOrWhiteSpace([Environment]::GetEnvironmentVariable('FEISHU_USER_ACCESS_TOKEN', 'Process'))) {
        throw 'FEISHU_USER_ACCESS_TOKEN is required when FeishuAuthMode=user.'
    }
    $dryRunText = & $FeishuWrapperPath -PackageCache $FeishuPackageCache -Domain $FeishuDomain -AuthMode $FeishuAuthMode -DryRun | Out-String
    $dryRunPlan = $dryRunText | ConvertFrom-Json
    if (-not [bool]$dryRunPlan.packagePresent -or -not [bool]$dryRunPlan.packageValidated) {
        throw "Locked Feishu package is absent or does not match the tool contract: $FeishuPackageCache"
    }
    if (-not [bool]$dryRunPlan.nodeReady) { throw 'Node.js >=20 is required before enabling Feishu.' }
    $secretValue = [Environment]::GetEnvironmentVariable('FEISHU_APP_SECRET', 'Process')
    if ($dryRunText -match [regex]::Escape($secretValue)) { throw 'Feishu wrapper dry-run exposed App Secret.' }
}

$template = Get-Content -LiteralPath $templatePath -Raw -Encoding UTF8
$feishuEnvironmentNames = @('FEISHU_APP_ID', 'FEISHU_APP_SECRET')
if ($FeishuAuthMode -eq 'user') { $feishuEnvironmentNames += 'FEISHU_USER_ACCESS_TOKEN' }
$renderedEnvironmentNames = '[' + (($feishuEnvironmentNames | ForEach-Object { ConvertTo-TomlString $_ }) -join ', ') + ']'
$replacements = @{
    '__FEISHU_ENABLED__' = $(if ($EnableFeishu) { 'true' } else { 'false' })
    '__FEISHU_WRAPPER__' = (ConvertTo-TomlString ([IO.Path]::GetFullPath($FeishuWrapperPath)))
    '__FEISHU_MCP_CACHE__' = (ConvertTo-TomlString ([IO.Path]::GetFullPath($FeishuPackageCache)))
    '__FEISHU_DOMAIN__' = (ConvertTo-TomlString $FeishuDomain.TrimEnd('/'))
    '__FEISHU_AUTH_MODE__' = (ConvertTo-TomlString $FeishuAuthMode)
    '__FEISHU_ENV_VARS__' = $renderedEnvironmentNames
}
foreach ($key in $replacements.Keys) { $template = $template.Replace($key, [string]$replacements[$key]) }
if ($template -match '__[A-Z0-9_]+__') { throw 'Rendered Feishu config still contains placeholders.' }
$lines.Add($template.Trim())
$content = ($lines -join [Environment]::NewLine) + [Environment]::NewLine
if ($content -match '(?i)(app[_-]?secret\s*=|FEISHU_APP_SECRET\s*=\s*["''][^"'']+)') {
    throw 'Refusing to render a literal App Secret.'
}

$outputFull = [IO.Path]::GetFullPath($OutputPath)
if ((Test-Path -LiteralPath $outputFull) -and -not $Overwrite) { throw "Output exists; use -Overwrite to replace it: $outputFull" }
$outputParent = Split-Path -Parent $outputFull
if (-not (Test-Path -LiteralPath $outputParent)) { New-Item -ItemType Directory -Force -Path $outputParent | Out-Null }
$tempPath = $outputFull + '.tmp-' + [guid]::NewGuid().ToString('N')
try {
    Set-Content -LiteralPath $tempPath -Value $content -Encoding UTF8
    $python = Get-Command python -ErrorAction SilentlyContinue
    if ($python) {
        & $python.Source -c "import pathlib,sys,tomllib; tomllib.loads(pathlib.Path(sys.argv[1]).read_text(encoding='utf-8-sig'))" $tempPath
        if ($LASTEXITCODE -ne 0) { throw 'Rendered TOML failed Python tomllib validation.' }
    }
    Move-Item -LiteralPath $tempPath -Destination $outputFull -Force
} finally {
    if (Test-Path -LiteralPath $tempPath) { Remove-Item -LiteralPath $tempPath -Force }
}

[ordered]@{
    output = $outputFull
    disabledSkills = $nonCore.Count
    enabledSkills = @($requestedSkills)
    feishuEnabled = [bool]$EnableFeishu
    containsSecrets = $false
} | ConvertTo-Json
